modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL=""
license="MIT"

[[mods]]
modId="witherutils"
version="${file.jarVersion}"
displayName="WitherUtils"
authors="helgenius, klangzwang"
description=""
displayURL=""
logoFile="witherutils.png"

[[dependencies.witherutils]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.witherutils]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
